### PR TITLE
Support inline HTML in markdown documents

### PR DESCRIPTION
**Pull request by WillDaSilva**
Since this is for creating a static site, there is no notable risk of
dangerous HTML being present in the markdown files. This allows for much
greater flexibility when writing markdown files, and fits nicely with
the no-config goal of ssg since it allows users to go outside the bounds
of markdown without having to configure anything; they can simply add
some HTML to their document.

### CODE REVIEW

**Comment by swyxio** [comment]
appreciate it :) tho im probably going to move to https://mdsvex.com/ once i rewrite this someday. do you need this urgently or are you just suggesting it? im not actively working on this right now

**Comment by WillDaSilva** [comment]
I wouldn't really call it "urgent", I'm using it right now for blog posts on my website (which is based off of [swyx.io](https://swyx.io/)). mdsvex looks really cool, but in the meantime allowing inline HTML would be useful, and translate over to the use of mdsvex well.

**Comment by swyxio** [comment]
alright i'm gonna merge it in but just fwiw i do want to do a total rewrite someday (haha.. final last words eh?) it is true that i could use this inside my own blog tho so thank you very much

**Comment by swyxio** [comment]
released as ssg@0.0.63

**Pull request merged**
